-- Test potentially problematic section
WITH test_data AS (
  SELECT 
    TO_DATE('2025-04-01') AS DATE_CATEGORY,
    100 AS "All Pixels",
    200 AS "9e90t3nOfBJS3oQuFn7MzI3v0G1s",
    300 AS "Wzlyy2fuuDSUiTmzhqIq4dGVV1QB"
)
SELECT 
  ARRAY_AGG(DATE_CATEGORY) WITHIN GROUP (ORDER BY DATE_CATEGORY ASC) AS DATE_CATEGORY,
  ARRAY_AGG("All Pixels") WITHIN GROUP (ORDER BY DATE_CATEGORY ASC) AS "All Pixels",
  ARRAY_AGG("9e90t3nOfBJS3oQuFn7MzI3v0G1s") WITHIN GROUP (ORDER BY DATE_CATEGORY ASC) AS "9e90t3nOfBJS3oQuFn7MzI3v0G1s",
  ARRAY_AGG("Wzlyy2fuuDSUiTmzhqIq4dGVV1QB") WITHIN GROUP (ORDER BY DATE_CATEGORY ASC) AS "Wzlyy2fuuDSUiTmzhqIq4dGVV1QB"
FROM (
  SELECT 
    DATE_CATEGORY,
    SUM(IFNULL("All Pixels", 0)) AS "All Pixels",
    SUM(IFNULL("9e90t3nOfBJS3oQuFn7MzI3v0G1s", 0)) AS "9e90t3nOfBJS3oQuFn7MzI3v0G1s",
    SUM(IFNULL("Wzlyy2fuuDSUiTmzhqIq4dGVV1QB", 0)) AS "Wzlyy2fuuDSUiTmzhqIq4dGVV1QB"
  FROM test_data
  GROUP BY DATE_CATEGORY
); 