-- Test quoted identifiers
WITH sample_data AS (
  SELECT 
    TO_DATE('2025-04-01') AS DATE_CATEGORY,
    100 AS "All Pixels",
    200 AS "9e90t3nOfBJS3oQuFn7MzI3v0G1s",
    300 AS "Wzlyy2fuuDSUiTmzhqIq4dGVV1QB"
)
SELECT 
  ARRAY_AGG(DATE_CATEGORY) WITHIN GROUP (ORDER BY DATE_CATEGORY ASC) AS DATE_CATEGORY,
  ARRAY_AGG("All Pixels") WITHIN GROUP (ORDER BY DATE_CATEGORY ASC) AS "All Pixels",
  ARRAY_AGG("9e90t3nOfBJS3oQuFn7MzI3v0G1s") WITHIN GROUP (ORDER BY DATE_CATEGORY ASC) AS "9e90t3nOfBJS3oQuFn7MzI3v0G1s",
  ARRAY_AGG("Wzlyy2fuuDSUiTmzhqIq4dGVV1QB") WITHIN GROUP (ORDER BY DATE_CATEGORY ASC) AS "Wzlyy2fuuDSUiTmzhqIq4dGVV1QB"
FROM sample_data; 