-- Test simplified query to identify the error
WITH sample_data AS (
  SELECT 
    TO_DATE('2025-04-01') AS DATE_CATEGORY,
    100 AS OCTANE_IMP,
    200 AS TV_IMP
  UNION ALL
  SELECT 
    TO_DATE('2025-04-08') AS DATE_CATEGORY,
    150 AS OCTANE_IMP,
    250 AS TV_IMP
)
SELECT 
  ARRAY_AGG(DATE_CATEGORY) WITHIN GROUP (ORDER BY DATE_CATEGORY ASC) AS DATE_CATEGORY,
  ARRAY_AGG(OCTANE_IMP) WITHIN GROUP (ORDER BY DATE_CATEGORY ASC) AS OCTANE_IMP,
  ARRAY_AGG(TV_IMP) WITHIN GROUP (ORDER BY DATE_CATEGORY ASC) AS TV_IMP
FROM sample_data; 