-- Test DISTINCT with ARRAY_AGG
WITH test_data AS (
  SELECT TO_DATE('2025-04-01') AS DATE_CATEGORY, 100 AS VALUE
  UNION ALL
  SELECT TO_DATE('2025-04-01') AS DATE_CATEGORY, 200 AS VALUE -- Duplicate date to test DISTINCT
  UNION ALL
  SELECT TO_DATE('2025-04-08') AS DATE_CATEGORY, 300 AS VALUE
)
SELECT DISTINCT
  ARRAY_AGG(DATE_CATEGORY) WITHIN GROUP (ORDER BY DATE_CATEGORY ASC) AS DATE_CATEGORY,
  ARRAY_AGG(VALUE) WITHIN GROUP (ORDER BY DATE_CATEGORY ASC) AS VALUE
FROM test_data; 